[package]
name = "Qiskit_RustKit"
version = "0.1.0"
authors = ["Snyata <core@synavate.tech>"]
license = "MIT/Apache-2.0"
readme = "README.md"
keywords = ["qml", "qc", "qiskit", "pytorch"]
repository = "https://github.com/orion"
homepage = "https://synavate.tech"
documentation = "https://docs.synavate.tech"
description = """
A rust implementation of the architecture around Python and Qiskit. Including the use of Mojo for Python code.
"""
categories = ["qiskit", "qml", "pytorch"]
edition = "2018"

[workspace]
members = ["unit_tests", "qiskit_algo", "qml_rustkit", "qiskit_bridge", "duh_ta", "quantilay"]

[dependencies]
log = "0.4.21"
serde = "1.0.97"
indexmap = { version = "2.2.6", optional = true }

[dev-dependencies]
serde_derive = "1.0"
serde_json = "1.0"


[features]
default = []

# Use indexmap rather than BTreeMap as the map type of toml::Value.
# This allows data to be read into a Value and written back to a TOML string
# while preserving the order of map keys in the input.
preserve_order = ["indexmap"]
